image: node:alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

typescript:
    script:
        - yarn install --frozen-lockfile
        - yarn tsc

lint:
    script:
        - yarn install --frozen-lockfile
        - yarn lint
